#!/bin/sh

if [ $# -ne 3 ]
then
  echo "Usage: `basename $0` username uid gid"
  exit 65
fi

TMPFILE="/tmp/ldif_${1}_create"

cat /root/ldap_group_create.ldif > $TMPFILE
cat /root/ldap_user_create.ldif >> $TMPFILE
sed -i "s/_GROUP_/${1}/" $TMPFILE
sed -i "s/_GID_/${3}/"   $TMPFILE
sed -i "s/_USER_/${1}/"  $TMPFILE
sed -i "s/_ID_/${2}/"    $TMPFILE
sed -i "s/_PASSWORD_/gdyb21LQTcIANtvYMT7QVQ==/" $TMPFILE
ldapadd -cxWD cn=admin,dc=docker,dc=local -f $TMPFILE
rm $TMPFILE

sleep 1 # wait for LDAP to store UID/GID

# create home directory
mkdir /srv/homes/$1
chown -R $1:$1 /srv/homes/$1
chmod 700 /srv/homes/$1
