#!/bin/sh

if [ $# -ne 2 ]
then
  echo "Usage: `basename $0` name gid"
  exit 65
fi

GRP="${1}_share"
TMPFILE="/tmp/ldif_${GRP}_create"

cat /root/ldap_group_create.ldif > $TMPFILE
sed -i "s/_GROUP_/${GRP}/" $TMPFILE
sed -i "s/_GID_/${2}/"     $TMPFILE
ldapadd -cxWD cn=admin,dc=docker,dc=local -f $TMPFILE
rm $TMPFILE

sleep 1 # wait for LDAP to store UID/GID

# create the directory and group
mkdir /srv/shares/$1
chmod g+s /srv/shares/$1 # default permissions user:group
chown root:$GRP /srv/shares/$1
chmod 770 /srv/shares/$1
