#!/bin/sh

if [ $# -ne 3 ]
then
  echo "Usage: `basename $0` container externalPort internalPort"
  exit 65
fi

IP=`docker inspect $1 | awk -F '"' '/IPAdd/ {print $4}'`
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport $2 -j DNAT --to $IP:$3
