#!/bin/sh

if [ $# -ne 2 ]
then
  echo "Usage: `basename $0` share user"
  exit 65
fi

GRP="${1}_share"
TMPFILE="/tmp/ldif_${GRP}_remove_${2}"

cat /root/ldap_user_remove_group.ldif > $TMPFILE
sed -i "s/_GROUP_/${GRP}/" $TMPFILE
sed -i "s/_USER/${2}/"     $TMPFILE
ldapmodify -cxWD cn=admin,dc=docker,dc=local -f $TMPFILE
rm $TMPFILE
